- hosts: iscsi_target
  become: true
  max_fail_percentage: 0
  gather_facts: no

  roles:
    - role: iscsi-target-setup
  tags: target, untagged

- hosts: iscsi_initiator
  become: true
  max_fail_percentage: 0
  gather_facts: no

  roles:
    - role: iscsi-initiator-setup
      tags: initiator, untagged

    - role: iscsi-device-mapper-setup
      tags: device-mapper, untagged
