## # yum install iscsi-initiator-utils
# this should be always installed by the standard installation
- name: install iscsi-initiator-utils
  yum:
    name: iscsi-initiator-utils
    state: present

## # systemctl enable iscsid.service
## # systemctl start iscsid.service
- name: enable and start iscsid.service
  service:
    name: iscsid.service
    state: started
    enabled: yes

## # cut -d '=' -f 2 /etc/iscsi/initiatorname.iscsi
- name: obtain initiator name
  command: >-
    cut -d '=' -f 2 /etc/iscsi/initiatorname.iscsi
  register: initiatorname
  changed_when: false
  failed_when: initiatorname.stdout == ''

## # (target host) targetcli /iscsi/TARGET_IQN/tpg1/acls create INITIATORNAME
- name: add ACL for the initiator
  delegate_to: "{{ groups['iscsi-target'][0] }}"
  command: >-
    targetcli /iscsi/{{ TARGET_IQN }}/tpg1/acls create {{ initiatorname.stdout }}
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "already exists" not in result.stderr

## # iscsiadm -m discovery -t st -p TARGET_PORTS[0,1]
- name: discovery the iscsi target
  command: >-
    iscsiadm -m discovery -t st -p {{ item }}
  with_items: "{{ TARGET_PORTS }}"

## # iscsiadm -m node -T TARGET_IQN -p TARGET_PORTS[0,1] -l
- name: login to the iscsi target
  command: >-
    iscsiadm -m node -T {{ TARGET_IQN }} -p {{ item }} -l
  with_items: "{{ TARGET_PORTS }}"
